version: "2.4"

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: products
    ports:
      - "4306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/products?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - microservices-net

  sales-service:
    image: fiammara/sales-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/products?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - microservices-net

  ui-service:
    build: ./ui-service
    ports:
      - "8080:8080"
    environment:
      PRODUCT_SERVICE_URL: http://product-service:8081/api/products
      SALES_SERVICE_URL: http://sales-service:8082/api/sales
    depends_on:
      product-service:
        condition: service_started
      sales-service:
        condition: service_started
    restart: on-failure
    networks:
      - microservices-net

volumes:
  mysql-data:

networks:
  microservices-net:
    driver: bridge





