apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
        - name: ui-service
          image: prod-ui-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:8081/api/products"
            - name: SALES_SERVICE_URL
              value: "http://sales-service:8082/api/sales"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
