product.service.url=http://localhost:8081/api/products
sales.service.url=http://localhost:8082/api/sales
user.service.url=http://localhost:8083/api/users
user.service.base-url=http://localhost:8083
user.service.users-path=/api/users
user.service.auth-path=/api/auth