product.service.url=http://product-service:8081/api/products
sales.service.url=http://sales-service:8082/api/sales
user.service.url=http://user-service:8083/api/users
user.service.base-url=http://user-service:8083
user.service.users-path=/api/users
user.service.auth-path=/api/auth